#!/bin/sh
#set -U SXHKD_SHELL sh
~/.bin/autostart.sh & # arandr stuff, tint2, redshift, nm-aplet, volumeicon, Nitrogen --restore, unclutter
xset -dpms & # old skool bs removal
Xset b off & #
xset s off & #
# 
sxhkd &
#                   Monitors desktops
bspc monitor HDMI-0 -d III IV V VI
bspc monitor eDP -d I II
#                   BSPWM configuration
#bspc config border_radius       8
bspc config border_width         4
bspc config window_gap           16	
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
#bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
# bspc config history_aware_focus  true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
#                   BSPWM coloring
bspc config focused_border_color "#595959" #lightGrey #"#5efcfe" #BrightBlue 
bspc config urgent_border_color "#00ffff" #"#dd2727" #Redish
bspc config normal_border_color "#3F3F3F" #DarkGrey
bspc config presel_feedback_color "#5E5B5B" #AnotherGrey
#                   Fullscreen applications
bspc rule -a gimp state=fullscreen
#                   Floating applications
bspc rule -a Arandr state=floating
#bspc rule -a feh state=floating
bspc rule -a nitrogen state=floating
bspc rule -a tint2conf state=floating
#                   Application workspace placment
bspc rule -a vlc desktop=^4
bspc rule -a vlc state=floating
bspc rule -a firefox desktop=^3
bspc rule -a qutebrowser desktop=^3
