#!/bin/sh
#set -U SXHKD_SHELL sh
~/.bin/autostart.sh & # tint2, redshift, nm-aplet, volumeicon. Nitrogen --restore , unclutter
xset -dpms &
Xset b off &
xset s off &
# 
sxhkd &
#                   Monitors desktops
bspc monitor HDMI-0 -d 3 4 5 6
bspc monitor eDP -d 1 2
#
#                   BSPWM configuration
#bspc config border_radius       8
bspc config border_width         1
bspc config window_gap           8	
bspc config top_padding          2
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
#bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
# bspc config history_aware_focus  true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
#                   BSPWM coloring
#bspc config normal_border_color		"#3F3F33"
#bspc config active_border_color		"#FF7373" #"#f1d6fc"
bspc config focused_border_color	 "#FF7373" #"#5efcfe"
#bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"
#                   Fullscreen applications
bspc rule -a gimp state=fullscreen
#                   Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a nitrogen state=floating
bspc rule -a tint2conf state=floating
#                   Application workspace placment
bspc rule -a vlc desktop=^4
bspc rule -a vlc state=floating
bspc rule -a firefox desktop=^3
bspc rule -a qutebrowser desktop=^3
