#!/bin/sh
#set -U SXHKD_SHELL sh
/home/johnvile/.bin/arandr-top.sh
xset -dpms &
Xset b off &
xset s off &
#           Wallpaper
nitrogen --restore
#           Autostart some stuff
tint2 &
#panel &
#redshift-gtk &
#volumeicon &
#nm-applet &
sxhkd &
#           Monitors desktops
bspc monitor HDMI-0 -d 3 4 5 6
bspc monitor eDP -d 1 2
#
#           BSPWM configuration
#bspc config border_radius       8
bspc config border_width         1
bspc config window_gap           8	
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         2
bspc config right_padding        2
#bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
# bspc config history_aware_focus  true
bspc config pointer_modifier mod1
bspc rule -a vlc state=floating
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
#           BSPWM coloring
#bspc config normal_border_color		"#3F3F33"
bspc config active_border_color		"#f1d6fc"
bspc config focused_border_color	"#5efcfe"
#bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"
#bspc rule -a dropdown sticky=on state=floating hidden=on
#termite --class dropdown -e "zsh -i" &
#           Fullscreen applications
#bspc rule -a inkscape state=fullscreen
#           Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a nitrogen state=floating

